# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wars Mirrors
# title: 北京外国语大学开源软件镜像站
school: WARS
# school: 北京外国语大学
brand: Wars Open Source Mirror
operator: Fives Group
# operator: 北外信息技术中心
logo: true
meow_404: true
issue_tag: tuna
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:categories/:title/"
url: "https://mirrors.wars.cat"
hostname: "mirrors.wars.cat"
urlv4: "https://mirrors.wars.cat"
urlv6: "https://mirrors.wars.cat"
aosp: "aosp.tuna.tsinghua.edu.cn"
arch_archive: "arch-archive.tuna.tsinghua.edu.cn"
aur: "aur.tuna.tsinghua.edu.cn"
pypi: "pypi.tuna.tsinghua.edu.cn"
homelink: "https://blog.wars.cat"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false


sass:
    sass_dir: static/css

gems:
    - jekyll-babel
    - jekyll-sitemap

babel_js_extensions: 'es6'

exclude: [Gemfile, Gemfile.lock, README.md, gen_robot.sh, vendor, geninfo/, gen_robot.sh, gen_desc.py, Dockerfile*]

# vim: ts=2 sts=2 sw=2 expandtab
